// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7DnrJAugsMZjUxPyfvWmPesweAEfLXW8',
    appId: '1:329763374959:web:86903427e22121ff34ca9a',
    messagingSenderId: '329763374959',
    projectId: 'kishandetails',
    authDomain: 'kishandetails.firebaseapp.com',
    storageBucket: 'kishandetails.appspot.com',
    measurementId: 'G-VXYMV8VT40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA58TvjJNJ0z-98ISG9wfkwxVqayDtDC5g',
    appId: '1:329763374959:android:d67f91f64dc2869134ca9a',
    messagingSenderId: '329763374959',
    projectId: 'kishandetails',
    storageBucket: 'kishandetails.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm1tfYyyzloxei2yri4rAwhUu6jSuTxEM',
    appId: '1:329763374959:ios:70eff9b6298a6cb634ca9a',
    messagingSenderId: '329763374959',
    projectId: 'kishandetails',
    storageBucket: 'kishandetails.appspot.com',
    iosBundleId: 'com.suis.plantdiseasedetector.plantDiseaseDetector',
  );
}
